"apiVersion": "v1"
"kind": "ConfigMap"
"metadata": 
  "name": "npm-proxy-config"
  
"data": 
  PROXY_REGISTRY_URI: {{ .values.global.PROXY_REGISTRY_URI | quote }}
  PROXY_REGISTRY_HOST: {{ .values.global.PROXY_REGISTRY_HOST | quote }}
  OIDC_ISSUER_URL: {{ .values.global.OIDC_ISSUER_URL | quote }}
  OIDC_CLIENT_ID: {{ .values.global.OIDC_CLIENT_ID | quote }}
  OIDC_REDIRECT_URL: {{ .values.global.OIDC_REDIRECT_URL | quote }}
