apiVersion: apps/v1
kind: Deployment
metadata: 
  name: npm-proxy-deployment
  
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: npm-proxy-deployment

  template: 
    metadata: 
      labels: 
        app: npm-proxy

    spec: 
      containers:         
        - name: npm-proxy
          image: ghcr.io/veto-party/npm-proxy:REPLACE-IMAGE
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: data
              mountPath: /opt/npm-proxy/cache

          resources:

          envFrom:
          - configMapRef:
              name: npm-proxy-config
          - secretRef:
              name: npm-proxy-secret

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: npm-proxy-pvc
