apiVersion: "v1"
kind: PersistentVolumeClaim
metadata:
  name: npm-proxy-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: "v1"
kind: PersistentVolumeClaim
metadata:
  name: npm-proxy-redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi